task: detection

num_classes: 8
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /Your path/AI-TOD/train/images/
    ann_file: /Your path/aitod_trainval_v1.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 2
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /Your path/AI-TOD/val/images/
    ann_file: /Your path/aitod_val_v1.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 4
  num_workers: 2
  drop_last: False